---
- name: Get Kafka Cluster ID
  include_tasks: tasks/get_cluster_id.yml

- name: Log into MDS API
  include_tasks: tasks/mds_rest_login.yml

- name: Grant Security Admin Role to Kafka Connect user
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{kafka_connect_principal}}/roles/SecurityAdmin"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      {"clusters":{"kafka-cluster":"{{cluster_id}}","connect-cluster":"{{ kafka_connect['properties']['group.id'] }}"}}
    status_code: 204

- name: Grant Connect user ResourceOwner on the group that Connect nodes use to coordinate across the cluster
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{kafka_connect_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      {"scope":{"clusters":{"kafka-cluster":"{{cluster_id}}"}},"resourcePatterns":[{"resourceType":"Group","name":"{{ kafka_connect['properties']['group.id'] }}","patternType":"LITERAL"}]}
    status_code: 204

- name: Grant Connect ResourceOwner on the Config topic where Connect configs are stored
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{kafka_connect_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    # TODO topic should not be hardcoded
    body: >
      {"scope":{"clusters":{"kafka-cluster":"{{cluster_id}}"}},"resourcePatterns":[{"resourceType":"Topic","name":"{{ kafka_connect['properties']['config.storage.topic'] }}","patternType":"LITERAL"}]}
    status_code: 204

- name: Grant Connect ResourceOwner on the offset storage topic
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{kafka_connect_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    # TODO topic should not be hardcoded
    body: >
      {"scope":{"clusters":{"kafka-cluster":"{{cluster_id}}"}},"resourcePatterns":[{"resourceType":"Topic","name":"{{ kafka_connect['properties']['offset.storage.topic'] }}","patternType":"LITERAL"}]}
    status_code: 204

- name: Grant Connect ResourceOwner on the status storage topic
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{kafka_connect_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    # TODO topic should not be hardcoded
    body: >
      {"scope":{"clusters":{"kafka-cluster":"{{cluster_id}}"}},"resourcePatterns":[{"resourceType":"Topic","name":"{{ kafka_connect['properties']['status.storage.topic'] }}","patternType":"LITERAL"}]}
    status_code: 204
