zookeeper:
  config:
    clientPort: 2181
broker:
  config:
    port: 9092
kafka:
  broker:
    config_file: /etc/kafka/server.properties
    systemd_file: /usr/lib/systemd/system/confluent-kafka.service
    systemd_override: /etc/systemd/system/confluent-kafka.service.d
    service_name: confluent-kafka
    datadir:
      - /var/lib/kafka/data
