- name: Schema Registry Upgrade
  hosts: schema_registry
  serial: 1
  # there is a schema registry leader, should think about the master/follower thing
  # look in schema reg docs
  tasks:
    - import_role:
        name: confluent.variables_handlers

    - name: Get Package Facts - RedHat
      package_facts:
        manager: auto
      when: ansible_os_family == "RedHat"

    - name: Set Current Package Version - RedHat
      set_fact:
        schema_registry_current_version: "{{ ansible_facts.packages['confluent-schema-registry'][0]['version'] }}"
      when: ansible_os_family == "RedHat"

    - name: Get Package Facts - Debian
      # Bug in ansible 2.8 with apt package manager and package_facts module
      # https://github.com/ansible/ansible/pull/56008
      # when above pull fixed, shouldn't need Debain v RedHat logic
      shell: apt list confluent-schema-registry -a | grep installed | cut -d ' ' -f2 | cut -d '-' -f1
      register: schema_registry_package_query
      when: ansible_os_family == "Debian"

    - name: Set Current Package Version - Debian
      set_fact:
        schema_registry_current_version: "{{ schema_registry_package_query.stdout }}"
      when: ansible_os_family == "Debian"

    - debug:
        msg: "Current version: {{schema_registry_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Schema Registry
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ schema_registry_service_name }}"
        packages: "{{ schema_registry_packages }}"
        backup_files:
          - "{{ schema_registry.config_file }}"
          - "{{ schema_registry.systemd_override }}"
        restore_files:
          - "{{ schema_registry.config_file }}"
      # when: schema_registry_current_version != confluent_package_version

    - name: Wait for API to return 200 - HTTP
      uri:
        url: "http://localhost:{{schema_registry_listener_port}}/config"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      when: not schema_registry_ssl_enabled|bool

    # - name: Wait for API to return 200 - HTTPS
    #  uri:
    #    url: "https://localhost:{{schema_registry_listener_port}}/config"
    #    status_code: 200
    #    validate_certs: no
    #  register: result
    #  until: result.status == 200
    #  retries: 60
    #  delay: 5
    # when: schema_registry_ssl_enabled|bool
