---
## Steps

- name: Upgrade Kafka
  hosts: broker
  serial: 1
  tasks:
  - import_role:
      name: confluent.upgrade.kafka-broker

# Eventually fix the properties file

# Upgrade Schema Registry,

# REST Proxy

# Camus (more below).
