---
- name: Upgrade Kafka
  hosts: broker
  serial: 1
  tasks:
  - import_role:
      name: confluent.upgrade.kafka-broker

- name: Update Kafka Post Steps
  hosts: broker
  serial: 1
  tasks:
  - import_role:
      name: confluent.upgrade.kafka-broker-post


# Upgrade Schema Registry,

# REST Proxy

# Camus (more below).
