---
- name: Get Kafka Cluster ID
  include_tasks: tasks/get_cluster_id.yml

- name: Log into MDS through CLI
  include_tasks: tasks/mds_cli_login.yml

- name: Create MDS ACLs
  shell: |
    /usr/local/bin/confluent iam acl create \
      --kafka-cluster-id {{cluster_id}} \
      --allow --principal User:{{ principal }} \
      --operation {{item.1}} \
      --{{item.0.resource_type}} {{item.0.resource_name}}
  loop: "{{ acls_list | subelements('operations')}}"
