---
- name: Get Kafka Cluster ID from Zookeeper
  shell: /bin/zookeeper-shell localhost:2181 get /cluster/id | grep version
  delegate_to: "{{ groups['zookeeper'][0] }}"
  register: cluster_id_query

- set_fact:
    cluster_id_json: "{{ cluster_id_query.stdout }}"

- set_fact:
    cluster_id: "{{ cluster_id_json.id }}"

- debug: var=cluster_id

- name: Login to MDS to get Security Token
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/authenticate"
    status_code: 200
    validate_certs: no
    url_username: "{{rbac_broker_admin}}"
    url_password: "{{rbac_broker_admin_password}}"
    force_basic_auth: true
  register: authentication_response

- set_fact:
    mds_token: "{{ authentication_response.json.auth_token }}"
