---
- name: Login to MDS to get Security Token
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/authenticate"
    status_code: 200
    validate_certs: no
    url_username: "{{rbac_broker_admin}}"
    url_password: "{{rbac_broker_admin_password}}"
    force_basic_auth: true
  register: authentication_response

- name: Set mds_token Variable
  set_fact:
    mds_token: "{{ authentication_response.json.auth_token }}"
