---
- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Create 2048-bit RSA Private key
  shell: |
    openssl genrsa \
      -out /var/ssl/private/generation/{{rbac_mds_private_key_filename}} 2048

- name: Extract Public key
  shell: |
    openssl rsa \
      -in /var/ssl/private/generation/{{rbac_mds_private_key_filename}} \
      -outform PEM -pubout \
      -out /var/ssl/private/generation/{{rbac_mds_public_key_filename}}

- name: Copy Generated SSL Files Back to Ansible Host
  synchronize:
    src: /var/ssl/private/generation/
    dest: generated_ssl_files
    mode: pull
