---
- name: Initialize the Client Properties Dict
  set_fact:
    client_properties: {}

- name: Add Security Protocol Variable
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'security.protocol': listener | kafka_protocol_defaults(sasl_protocol, ssl_enabled)
      }
    ) }}"

- name: Add SSL Variables
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'ssl.truststore.location': truststore_path,
        config_prefix + 'ssl.truststore.password': truststore_storepass
      }
    ) }}"
  when: listener['ssl_enabled'] | default(ssl_enabled) | bool

- name: Add MTLS Variables
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'ssl.keystore.location': keystore_path,
        config_prefix + 'ssl.keystore.password': keystore_storepass,
        config_prefix + 'ssl.key.password': keystore_keypass
      }
    ) }}"
  when: listener['ssl_mutual_auth_enabled'] | default(ssl_mutual_auth_enabled) | bool

- name: Add PKCS12 Variables
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'ssl.keymanager.algorithm': 'PKIX',
        config_prefix + 'ssl.trustmanager.algorithm': 'PKIX',
        config_prefix + 'ssl.keystore.type': 'pkcs12',
        config_prefix + 'ssl.truststore.type': 'pkcs12'
      }
    ) }}"
  when: listener['pkcs12_enabled'] | default(pkcs12_enabled) | bool

- name: Add Sasl Plain Variables
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'sasl.mechanism': 'PLAIN',
        config_prefix + 'sasl.jaas.config': 'org.apache.kafka.common.security.plain.PlainLoginModule required
          username=\"' + sasl_plain_username + '\" password=\"' + sasl_plain_password + '\";'
      }
    ) }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'PLAIN'

- name: Add Sasl SCRAM Variables
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'sasl.mechanism': 'SCRAM-SHA-256',
        config_prefix + 'sasl.jaas.config': 'org.apache.kafka.common.security.scram.ScramLoginModule required
          username=\"' + sasl_scram_username + '\" password=\"' + sasl_scram_password + '\";'
      }
    ) }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'SCRAM-SHA-256'

- name: Add Sasl GSSAPI Variables
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'sasl.mechanism': 'GSSAPI',
        config_prefix + 'sasl.kerberos.service.name': kerberos_kafka_broker_primary,
        config_prefix + 'sasl.jaas.config': 'com.sun.security.auth.module.Krb5LoginModule required
           useKeyTab=true storeKey=true keyTab=\"' + kerberos.keytab_dir + '/' + kerberos_keytab_path | basename '\"
           principal=\"' + kerberos_principal + '\";'
      }
    ) }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Add Sasl OAUTHBEARER Variables
  set_fact:
    client_properties: "{{ client_properties | combine(
      {
        config_prefix + 'sasl.mechanism': 'OAUTHBEARER',
        config_prefix + 'sasl.login.callback.handler.class': 'io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler'
        config_prefix + 'sasl.jaas.config': org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
           username=\"' + oauth_username + '\" password= \"' + oauth_password + '\"
           metadataServerUrls=\"' + mds_http_protocol + '://' + groups['kafka_broker'] | join(':' + mds_port|string + ',' + mds_http_protocol + '://') + ':' + mds_port|string + '\";'
      }
    ) }}"
  when: listener['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'OAUTHBEARER'
