- name: yum-clean-all
  command: yum clean all
  args:
    warn: no
  when: ansible_os_family == "RedHat"

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart kafka
  systemd:
    name: "{{kafka.broker.service_name}}"
    state: restarted
