- name: Set inter.broker.protocol.version
  lineinfile:
    path: "{{kafka.broker.config_file}}"
    regexp: 'inter.broker.protocol.version=.*'
    line: 'inter.broker.protocol.version=2.1'

- name: Set log.message.format.version
  lineinfile:
    path: "{{kafka.broker.config_file}}"
    regexp: 'log.message.format.version=.*'
    line: 'log.message.format.version=2.1'

- name: Create backup directory
  file:
    path: "{{kafka.broker.backup_dir}}"
    state: directory
    mode: 0755

- name: Backup /etc/kafka
  copy:
    src: "{{ item }}"
    dest: "{{kafka.broker.backup_dir}}/{{ item | basename }}"
    remote_src: yes
  with_items:
    - "{{ kafka.broker.config_file }}"
    # - "{{ kafka.broker.systemd_file }}"

- name: Stop kafka
  systemd:
    name: "{{kafka.broker.service_name}}"
    state: stopped

- name: Remove old confluent-kafka package
  yum:
    name: "{{kafka.new_package_name}}"
    state: absent

- name: Remove Confluent Dist Yum Repo
  yum_repository:
    name: Confluent.dist
    file: confluent
    state: absent
  notify: yum-clean-all

# - name: Remove Confluent Yum Repo
#   yum_repository:
#     name: Confluent
#     file: confluent
#     state: absent
#   notify: yum-clean-all

- name: Correct Confluent Yum Repo
  yum_repository:
    name: Confluent
    file: confluent
    description: "Confluent repository"
    baseurl: "{{confluent.repository.redhat.main.baseurl}}"
    gpgcheck: "{{confluent.repository.redhat.main.gpgcheck}}"
    gpgkey: "{{confluent.repository.redhat.main.gpgkey}}"
    enabled: "{{confluent.repository.redhat.main.enabled}}"
  notify: yum-clean-all

- meta: flush_handlers

# - name: Replace confluent.repo
#   copy:
#     src: confluent.repo
#     dest: /etc/yum.repos.d/confluent.repo
#     owner: root
#     group: root
#     mode: 0644
#
# - name: Refresh repository metadata
#   command: yum clean all

- name: Install new confluent-kafka package
  yum:
    name: "{{kafka.new_package_name}}"
    state: latest
  notify: reload systemd

- name: Restore /etc/kafka
  copy:
    src: "{{kafka.broker.backup_dir}}/{{ item | basename }}"
    dest: "{{ item }}"
    remote_src: yes
  with_items:
    - "{{kafka.broker.config_file}}"
    # - "{{ kafka.broker.systemd_file }}"

# - name: Reload systemd
#   command: systemctl daemon-reload

- meta: flush_handlers

- name: Restart kafka
  systemd:
    name: "{{kafka.broker.service_name}}"
    state: restarted
