---
- name: Get Kafka Cluster ID
  include_tasks: tasks/get_cluster_id.yml

- name: Log into MDS API
  include_tasks: tasks/mds_rest_login.yml

- name: Grant Security Admin Role to KSQL User
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{ksql_principal}}/roles/SecurityAdmin"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      {"clusters":{"kafka-cluster":"{{cluster_id}}","ksql-cluster":"{{ ksql['properties']['ksql.service.id'] }}"}}
    status_code: 204

- name: Grant Resource owner of KSQL Cluster on KSQL User
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{ksql_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      {"scope": {"clusters": {"kafka-cluster":"{{cluster_id}}","ksql-cluster":"{{ ksql['properties']['ksql.service.id'] }}"}},"resourcePatterns":[{"resourceType": "KsqlCluster","name": "ksql-cluster"}]}
    status_code: 204

- name: Grant ksql user the ResourceOwner role with three resourcePatterns
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{ksql_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      {"scope": {"clusters": {"kafka-cluster":"{{cluster_id}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "_confluent-ksql-default__command_topic","patternType":"LITERAL"},{"resourceType":"Topic","name":"default_-ksql_processing_log","patternType":"LITERAL"},{"resourceType":"Group","name":"_confluent-ksql-default_","patternType":"PREFIXED"}]}'
    status_code: 204
