---
- name: Copy MDS Private Key to Host
  copy:
    src: "generated_ssl_files/{{rbac_mds_private_key_filename}}"
    dest: "/var/ssl/private/{{rbac_mds_private_key_filename}}"

- name: Copy MDS Public Key to Host
  copy:
    src: "generated_ssl_files/{{rbac_mds_public_key_filename}}"
    dest: "/var/ssl/private/{{rbac_mds_public_key_filename}}"
