---
- name: Log into MDS through CLI
  include_tasks: tasks/mds_cli_login.yml
  when: acls_enabled|bool

- name: Create MDS ACLs
  shell: |
    /usr/local/bin/confluent iam acl create \
      --kafka-cluster-id {{cluster_id}} \
      --allow --principal User:{{ schema_registry_principal }} \
      --operation {{item.operation}} \
      --{{item.resource_type}} {{item.resource_name}}
  loop: "{{ schema_registry_acls }}"
  when: acls_enabled|bool
