---
- name: Get Kafka Cluster ID
  include_tasks: tasks/get_cluster_id.yml

- name: Log into MDS API
  include_tasks: tasks/mds_rest_login.yml

- name: Grant Security Admin Role to Schema Registry user
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{schema_registry_principal}}/roles/SecurityAdmin"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      {"clusters":{"kafka-cluster":"{{cluster_id}}","schema-registry-cluster":"schema-registry"}}
    status_code: 204

- name: Grant Schema Registry ResourceOwner on the group that Schema Registry nodes use to coordinate across the cluster
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{schema_registry_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      {"scope":{"clusters":{"kafka-cluster": "{{cluster_id}}"}}, "resourcePatterns":[{"resourceType":"Group","name": "schema-registry","patternType":"LITERAL"}]}
    status_code: 204

- name: Grant schema registry ResourceOwner on the kafka topic where schemas are stored
  uri:
    url: "http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{schema_registry_principal}}/roles/ResourceOwner/bindings"
    method: POST
    headers:
      Authorization: "Bearer {{mds_token}}"
      Content-Type: application/json
    body_format: json
    body: >
      { "scope": {"clusters": {"kafka-cluster":"{{cluster_id}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "_schemas" }]}
    status_code: 204
