---
- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.variables

    - name: Delete Tar
      file:
        state: absent
        path: "{{ confluent_archive_file_source }}"
