---
- name: Add Kerberos Properties
  set_fact:
    zookeeper_properties: "{{ zookeeper_properties | combine(zookeeper_sasl_kerberos_properties, recursive=True) }}"
  when: zookeeper_sasl_protocol == 'kerberos'

- name: Add Zookeeper Hosts
  set_fact:
    zookeeper_properties: "{{ zookeeper_properties | combine( {
      'server.' + hostvars[item]['zookeeper_id'] | default(groups.zookeeper.index(item) + 1) | string :
      item + ':' + zookeeper_peer_port|string + ':' + zookeeper_leader_port|string
    } ) }}"
  with_items: "{{ groups['zookeeper'] }}"
  when: item != inventory_hostname

- name: Add Zookeeper Hosts
  set_fact:
    zookeeper_properties: "{{ zookeeper_properties | combine( {
      'server.' + hostvars[item]['zookeeper_id'] | default(groups.zookeeper.index(item) + 1) | string :
      zookeeper_current_node_hostname + ':' + zookeeper_peer_port|string + ':' + zookeeper_leader_port|string
    } ) }}"
  with_items: "{{ groups['zookeeper'] }}"
  when: item == inventory_hostname

- name: Add Custom Properties
  set_fact:
    zookeeper_properties: "{{ zookeeper_properties | combine(zookeeper_custom_properties, recursive=True) }}"
