---
- name: Restart Zookeeper Service
  systemd:
    name: "{{zookeeper_service_name}}"
    enabled: true
    state: restarted

- name: Zookeeper Health Check
  include_tasks: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
